### PR TITLE
library for talking to the MPL115A2

### PR DESCRIPTION
**Pull request by asciiphil**
I wrote a library for the MPL115A2.  I thought it might be nice to get the code into the upstream repo.

My code is released under a CC0 waiver (http://creativecommons.org/publicdomain/zero/1.0/), so you can do whatever you'd like with it.

### CODE REVIEW

**Comment by improti** [comment]
We are talking MPL3115A2 here, aren't we? In the opposite to MPL115A2 as stated in title and issue.

**Comment by asciiphil** [comment]
What I have is an MPL115A2.  I ordered it from here: https://www.adafruit.com/products/992

**Comment by improti** [comment]
Yeah, MPL115A2 is different to MPL3115A2. Thx for pointing that out. There does not seem to be raspi-code around for the latter. Will see that I get my stuff uploaded, I at least have it running "somehow" ... 

But it seems the Adafruit repository is not really getting much love, is it? Your request is from 2013, you got a reaction in 2014, and I think we might have 2015 now?

**Comment by asciiphil** [comment]
@tdicola This code still works (apparently) correctly for me on my MPL115A2, which is wired exactly the way you describe yours.  Can you update to my latest code, rerun your tests with the MPL115A2 class's `debug` parameter set to `True`, and tell me what its output is?  I'd like to see what you're getting from the sensor's registers.

**Comment by unic8s** [comment]
@asciiphil I tested your code today. I used a very plain and clean setup for testing but I got the same problems which @tdicola got.

This is the output of the temperature values:

22.0093457944
-25.8411214953
-25.8411214953
22.1962616822
-25.6542056075
22.1962616822
117.897196262
22.1962616822
22.1962616822
22.1962616822
70.046728972
-25.6542056075
117.710280374
69.8598130841
22.0093457944
22.0093457944
22.0093457944
-25.8411214953
117.710280374

**Comment by asciiphil** [comment]
@unic8s Can you initialize the MPL115A2 class with `debug=True` and tell me what that prints out?  I want to see what actual values the class is getting over the I2C bus.

**Comment by neshaman** [comment]
Hi, I'm new to Pi world, but is there the library for the MPL3115A2 ?

Thanks

**Comment by neshaman** [comment]
I found the python library for MPL3115A2
https://github.com/ControlEverythingCommunity/MPL3115A2/blob/master/Python/MPL3115A2.py

**Comment by ladyada** [comment]
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>

**Pull request closed without merging**
