### PR TITLE
Create Adafruit_QuadAlphanum.py

### PR DESCRIPTION
**Pull request by fschioler**
Hi.

I missed code in the Raspberry Pi library for handling quad alphanumeric displays.
An implementation based on the LEDBackpack is attached.

Best regards
Fredrik Schiøler

### CODE REVIEW

**Comment by oberstet** [comment]
@fschioler Thanks for this code! Wondering why Adafruit isn't merging the many, many PRs ..

**Comment by ladyada** [comment]
we're in the process of splitting this library into multiple, manageable repositories that will be PEP8, py2/3 compat, and in pypi
it is a ton of work, no ETA for finishing...py3 compatibility in particular is hairy but we want to get that working before adding more code

**Comment by oberstet** [comment]
@ladyada Thanks for replying - sounds good! pep8, py3 .. yay. FWIW, I've got my stuff working https://twitter.com/oberstet/status/706167559981305856 using above PR .. real-time display of votes from the Web. The display is nice and easy to use. Thanks for that too!

**Comment by ladyada** [comment]
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>

**Pull request closed without merging**
